### ISSUE TITLE
owocr not working on Steam Deck with Big Picture

### ISSUE THREAD

**Issue by Keksus1** [AuroraWright/owocr#3]
Seems like owocr has problems capturing the screen when using it with Steam Big Picture. Tried running it with a script which starts owocr and RetroDeck at the same time. It works with desktop mode (where obviously RetroDeck isn't running particularly well) but no chance with big picture it seems.

ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
01:35:17.956 | Parsed config file
01:35:17.957 | Google Lens ready
01:35:17.957 | manga-ocr not available, Manga OCR will not work!
01:35:18.018 | Reading from screen capture, writing to websocket using Google Lens
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/deck/.local/lib/python3.11/site-packages/owocr/__main__.py", line 23, in <module>
    main()
  File "/home/deck/.local/lib/python3.11/site-packages/owocr/__main__.py", line 19, in main
    fire.Fire(run)
  File "/home/deck/.local/lib/python3.11/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/owocr/run.py", line 907, in run
    sct_img = sct.grab(sct_params)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/mss/base.py", line 90, in grab
    screenshot = self._grab_impl(monitor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/mss/linux.py", line 427, in _grab_impl
    ximage = self.xlib.XGetImage(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/mss/linux.py", line 229, in _validate
    raise ScreenShotError(f"{func.__name__}() failed", details=details)
mss.exception.ScreenShotError: XGetImage() failed

**Comment by AuroraWright** [comment]
This seems like a mss issue (the module owocr uses to take screenshots on Linux), you should try reporting it to https://github.com/BoboTiG/python-mss

**Comment by AuroraWright** [comment]
A friend said it uses wayland which is not currently supported by mss https://github.com/BoboTiG/python-mss/issues/155
She also wrote this which might be of help here https://github.com/marissa999/steam-showots

**Comment by AuroraWright** [comment]
Closing here since this should just work without changes as soon as mss is updated to support Wayland
