### ISSUE TITLE
[BUG] writing to websocket isn't working

### ISSUE THREAD

**Issue by kamperemu** [AuroraWright/owocr#5]
The websocket isn't being run. Instead it throws this error.

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\site-packages\owocr\run.py", line 132, in run
    start_server = websockets.serve(self.server_handler, '0.0.0.0', config.get_general('websocket_port'), max_size=1000000000)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\site-packages\websockets\asyncio\server.py", line 737, in __init__
    self.server = Server(
                  ^^^^^^^
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\site-packages\websockets\asyncio\server.py", line 281, in __init__
    self.loop = asyncio.get_running_loop()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
```

**Comment by graingert** [comment]
The code should look like this:

```py
class WebsocketServerThread(threading.Thread):
    def __init__(self, read):
        super().__init__()
        self.daemon = True
        self._loop = None
        self.read = read
        self.clients = set()
        self._event = threading.Event()
        
    @property
    def loop(self):
        self._event.wait()
        return self._loop

    async def send_text_coroutine(self, text):
        for client in self.clients: I'm
            await client.send(text)

    async def server_handler(self, websocket):
        self.clients.add(websocket)
        try:
            async for message in websocket:
                if self.read and not paused:
                    websocket_queue.put(message)
                    try:
                        await websocket.send('True')
                    except websockets.exceptions.ConnectionClosedOK:
                        pass
                else:
                    try:
                        await websocket.send('False')
                    except websockets.exceptions.ConnectionClosedOK:
                        pass
        except websockets.exceptions.ConnectionClosedError:
            pass
        finally:
            self.clients.remove(websocket)

    def send_text(self, text):
        return asyncio.run_coroutine_threadsafe(self.send_text_coroutine(text), self.loop)

    def stop_server(self):
        self.loop.call_soon_threadsafe(self._stop_event.set)

    def run(self):
        async def main():
            self._loop = asyncio.get_running_loop()
            self._stop_event = stop_event = asyncio.Event()
            self._event.set()
            self.server = start_server = websockets.serve(self.server_handler, '0.0.0.0', config.get_general('websocket_port'), max_size=1000000000)
            async with start_server:
                await stop_event.wait()
        asyncio.run(main())
```

**Comment by kamperemu** [comment]
here's the error after quitting
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Scripts\owocr.exe\__main__.py", line 7, in <module>
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\site-packages\owocr\__main__.py", line 19, in main
    fire.Fire(run)
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\site-packages\fire\core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\site-packages\fire\core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\site-packages\fire\core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\site-packages\owocr\run.py", line 1002, in run
    websocket_server_thread.stop_server()
  File "C:\Users\kamper\AppData\Local\Programs\Python\Python312\Lib\site-packages\owocr\run.py", line 127, in stop_server
    self.loop.call_soon_threadsafe(self.server.ws_server.close)
                                   ^^^^^^^^^^^
AttributeError: 'WebsocketServerThread' object has no attribute 'server'
```

**Comment by graingert** [comment]
It looks like you didn't copy across my implementation of stop_server

**Comment by kamperemu** [comment]
> It looks like you didn't copy across my implementation of stop_server
your implementation works, I was sending the error to the author based on direct communication with them.

**Comment by graingert** [comment]
@kamperemu you should make a PR with the fixes

**Comment by graingert-coef** [comment]
You might want to use an anyio.BlockingPortal which does somewhat the same thing

**Comment by AuroraWright** [comment]
Fixed by https://github.com/AuroraWright/owocr/commit/1897324de2c3431a4d594bdb080cb34e651cd644 , anyone running into this can upgrade with `pip install --upgrade owocr` closing here but pinning it for visibility.
